new branch with new footer logo - to be cont...
theglobechurch/globe-static pull request #6
Opened 2022-11-15 23:03 UTC by MazOneTwoOne

2022-11-24 07:25 UTC, jamesdoc commented
Reviewing this; Realised that the logo that I gave you just wasn't going to behave properly with `rotate-90` – I want the logo snug against the right edge, so I've pushed an updated logo where the rotation is baked into the graphic (and the circle is cropped too) to the branch.

It's now sitting like this:

<img width="853" alt="Screenshot 2022-11-24 at 07 14 59" src="https://user-images.githubusercontent.com/790343/203718871-1e08c8c0-49d0-47aa-b34a-7d41e188562c.png">

A couple of minor tweaks that would be good to resolve here:

1. To get the logo where it is I `flex`ed the whole `<footer>`. This means that the top border extends too far now :( Can you move that down onto the `nav` 
2. The `flex` now means that the `nav` doesn't require the max-width on it.

With these two in, I think that we can swash and merge 👍

2022-11-24 07:28 UTC, jamesdoc requested changes

2022-11-24 07:28 UTC, jamesdoc commented on src/_includes/blocks/footer.njk
> +          <li><a  href="/the-globe-church">The Globe Church</a></li>
In all these links there is a weird extra space between the `a` and the first property (eg `href`). Would be good to resolve that for all of the items.

2022-11-24 22:26 UTC, MazOneTwoOne commented
- Top border adjusted, still used a max width to make sure it didn't overlap with logo. Looks like this now;
<img width="814" alt="Screenshot 2022-11-24 at 22 24 50" src="https://user-images.githubusercontent.com/76905544/203870117-b8166086-95f8-4ac5-9c04-7dd8da57254d.png">


- spaces between `a` and `href` now formatted.

2022-11-25 10:17 UTC, jamesdoc approved these changes
Looks good; please squash and merge 👍

2022-11-25 22:42 UTC, merged